### PR TITLE
Eol annnotation

### PR DESCRIPTION
**Pull request by ecofriendlygeek**
Hello nyamatongwe,
I have created new function for drawing EOL annotation similar to DrawFoldDisplayText.
Tested:
1. overlap with Fold text
2. visible line ends
3. wrapped lines
4. spacing
scite_eol2

Please review.
Thanks.

### CODE REVIEW

**Comment by nyamatongwe** [comment]
That is mostly working with the features I tried it with.

The most obvious issue is that the margin text should be limited to stMargin.length as it is not NUL-terminated. This makes it end with garbage like

EOLAnnotationNoNUL

This Lua script can be used to produce examples:
~~~lua
function ShowEOLAnnotations()
	editor.FoldDisplayTextStyle = ANNOTATION_BOXED
        local line = editor:LineFromPosition(editor.SelectionStart)
	editor.MarginStyle[line] = 8
	editor.MarginText[line] = "Annotation of line " .. line
end
~~~

It is also only ever using the STYLE_FOLDDISPLAYTEXT style which seems limiting - I would have expected it to use stMargin.style or even better allow multiple styles with stMargin.styles.

**Comment by ecofriendlygeek** [comment]
I fixed the null termination bug and using stMargin.style now.
I tested the equivalent with C code of the Lua code you gave as I 
got error Global editor is nil with Lua code, do you know how to fix this ?

**Comment by nyamatongwe** [comment]
OK, that looks better. In the code there was a change of type for foldDisplayText to string. It can remain a string_view as that avoids memory allocation and the graphics methods respect the length of string_view. So:
~~~cpp
    const std::string_view foldDisplayText(text, stMargin.length);
~~~

The expression for determining whether to box is weird - I'd expect just one of the clauses so perhaps its time to add an API so that there is an independent place to store this.
~~~cpp
if (vsDraw.annotationVisible == ANNOTATION_BOXED || model.foldDisplayTextStyle == SC_FOLDDISPLAYTEXT_BOXED ...
~~~

'text2' needs a more descriptive name.

Are you planning on supporting multiple styles in an EOL annotation? I'd expect that to be a common need so the application could display something like
subLineStart = 0; [**Error:** no declaration for _subLineStart_]

**Comment by ecofriendlygeek** [comment]
I shall change the type of string (assume it is safe to alter the length in string_view without altering the original string).
Will change the naming convention for text2.
Can you help in describing the API needed  ?
Should the margin annotation API's be duplicated or something else?
Your example is good, however, we don't need the multiple styles right now.
Need to get this merged back to the main source-forge scintilla first.

**Comment by nyamatongwe** [comment]
Copying the annotation APIs and the storage implementation in LineAnnotation would be reasonable along with the Annotation documentation. However, these implement storage of multiple styles (SCI_ANNOTATION[SG]ETSTYLES) so you could drop those APIs.

The multiple lines support and SCI_ANNOTATIONGETLINES API may not be wanted although I could imagine long texts being wrapped onto multiple lines, pushing following lines down. That would be complex. Or maybe they overlay following lines and have a show/reveal extra lines toggle.

Reexamined the naming in the patch and there's more to fix since it looks like the names (and comments) weren't changed from their source: foldDisplayText is actually annotation text and text2 is actually fold display text.

**Comment by ecofriendlygeek** [comment]
I will first work on the API's, then once done, can move to docs (not sure where that is to be done, you can let me know when I get there).

Shall take care of all naming related issues.

**Comment by ecofriendlygeek** [comment]
Hello nyamatongwe
API is checked in. Please review.
Tested as follows with ScintillaTest
         SSM(SCI_EOLANNOTATIONSETTEXT,0,(sptr_t)"Test EOL Annotation");
         SSM(SCI_EOLANNOTATIONGETTEXT,0,(sptr_t)buf);
         printf("%s\n", buf);
         SSM(SCI_STYLESETBOLD,512,1);
         SSM(SCI_EOLANNOTATIONSETSTYLE,0,512);
         int style=1;
         style=SSM(SCI_EOLANNOTATIONGETSTYLE,0,0);
         printf("style %d\n",style);

ScintillaTest

**Comment by ecofriendlygeek** [comment]
Doc (html and png) is also checked in. Please review.

**Comment by ecofriendlygeek** [comment]
eolann_doc

**Comment by nyamatongwe** [comment]
eolAnnotationStyleOffset doesn't seem to be taken account of apart from the call to ValidStyledText. It should be added to stEOLAnnotation.style to index styles.

In two-phase drawing, the background colour of the style isn't showing as drawBack is turned off before the call to DrawEOLAnnotationText. See the way DrawFoldDisplayText is called twice. Then ensure DrawEOL doesn't overdraw the background colour.

In the documentation, the image should make the annotation more distinct. Maybe have 2 examples in the image.

There is a type conversion warning for 64-bit builds:
~~~cpp
EditView.cxx(1334,77): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
~~~

SC_MODEVENTMASKALL is wrong as the new flag bit isn't ored into the correct place.

The 'text' variable isn't needed and just adds unnecessary code:
~~~cpp
const StyledText stEOLAnnotation = model.pdoc->EOLAnnotationStyledText(line);
if (!stEOLAnnotation.text || !ValidStyledText(vsDraw, vsDraw.eolAnnotationStyleOffset, stEOLAnnotation)) {
	return;
}
const std::string_view eolAnnotationText(stEOLAnnotation.text, stEOLAnnotation.length);
~~~

**Comment by ecofriendlygeek** [comment]
Fixed all the bugs and tested all the fixes / api's and updated the doc.
If no further issues, please advise how to merge.

eol_api


eolannotation

**Comment by nyamatongwe** [comment]
There are problems with virtual space being applied to the positions of both fold display text then again to the EOL annotation. See "function xx" in the image. Turn on virtual space in SciTE with virtual.space=3 then move the caret past the line end. It may be better to calculate positions in LayoutLine then just use them in the different Draw... methods as the current technique increases coupling between the Draw... methods.

Wrapping the text results in black areas on the first display line such as the third line of the image.

EOLWrap

**Comment by ecofriendlygeek** [comment]
I will fix the bugs you pointed out.I am having to manually merge between this fork which is quite old and the latest version of Scintilla and Scite on scintilla.org which I use to test.Can you suggest the best way to overcome the above ?

    On Saturday, 9 May, 2020, 9:36:42 am IST, Neil Hodgson <notifications@github.com> wrote:  
 
 


There are problems with virtual space being applied to the positions of both fold display text then again to the EOL annotation. See "function xx" in the image. Turn on virtual space in SciTE with virtual.space=3 then move the caret past the line end. It may be better to calculate positions in LayoutLine then just use them in the different Draw... methods as the current technique increases coupling between the Draw... methods.

Wrapping the text results in black areas on the first display line such as the third line of the image.

**Comment by ecofriendlygeek** [comment]
Forked on sourceforge and put all the changes from here to this commit.
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/f7a27facbb714cf51f084a9480a4f102c8cebedb/
How to send you review requests in future ?

**Comment by nyamatongwe** [comment]
Your SourceForge branch is easy to access and use. It helps to be branched from a recent point in Scintilla's repository.

You can notify me through replies here or on the mailing list when you commit to the branch.

Scintilla.iface is the main specification of the interface and scripts are used to generate Scintilla.h and other interface code (like scite/src/ScintillaCall.[cxx|h]). The Scintilla.h file in the patch doesn't appear to be generated by scripts/HFacer.py from Scintilla.iface as the new values aren't in the same location (just after AnnotationGetStyleOffset) and SC_MODEVENTMASKALL in Scintilla.iface hasn't been fixed like it was in Scintilla.h.

The new API values will also be renumbered to start at (probably) 2740. The 4000-4999 range is for lexing features.

**Comment by hs-apotell** [comment]
Committed a new branch "r756380" which is the latest commit in sourceforge as of 05/18.

@ecofriendlygeek You can prepare your pull request against this branch when ready.

**Comment by ecofriendlygeek** [comment]
**@nyamatongwe**  Please reviewLatest commit on
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/default/tree/
1. Fixed header and interface
2. Fixed virtual space with fold text
3. Fixed junk drawn when wrapping

**Comment by nyamatongwe** [comment]
There is an issue when a selection covers the line end and there is both a fold text and an EOL annotation. The extra aveCharWidth space added in this case on line 1321 does not appear to be completely handled by the EOL Annotation code.
EOLBoth

The trackLineWidth section doesn't work when the window is scrolled horizontally. However, this bug is also present for fold text which this code was copied from so [bug #2177](https://sourceforge.net/p/scintilla/bugs/2177/) has been reported. This problem does not need to be fixed for inclusion. Since the code works when the window has not been scrolled, it should remain. There is a comment that was also copied and should be updated.

**Comment by ecofriendlygeek** [comment]
@nyamatongwe : corrected the comment and the space.
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/7170c989c9e871507122333b73948b50b7ca3fec/

**Comment by nyamatongwe** [comment]
The point of my previous message was that, since the selection shading was affecting the EOL annotation, it should continue over the additional space rather than leave a hole. The most recent commit changed the colour of the space to the annotation background colour instead of extending the selection background. It looks like this:
EOLBack

It may be better for the selection shading to not affect the EOL annotation, since it is commentary on the text and not an integral part of the text. I don't have a strong opinion on this so its OK to decide either way but be consistent within the domain of the EOL annotation. This may just be a copy from the fold text code which performs selection shading as desired by its author.

**Comment by ecofriendlygeek** [comment]
scintilla_eol_selection
My picture is different from yours. Am I missing something ?

**Comment by ecofriendlygeek** [comment]
Just made a small change.
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/ef2d7297acf3cea3521926a2f4cff019eae8d2af/
If it looks fine, can remove the selection code from EOLAnnotation.

Running SciTE with lua does not work for me as I always get editor = nil error.

scintilla_eol_selection_fixed

**Comment by nyamatongwe** [comment]
To reproduce the issue I mentioned, there should be both an EOL annotation and the line should be folded with some fold display text.

Main elements for Lua to work are for the code to be in a function (Lua environment may not be completely ready at startup) and have the correct subsystem (3 or 7) so its run by SciTE's internal Lua interpreter, not a command line Lua.

To add new APIs like EOLAnnotationText into SciTE, the scite/scripts/IFaceTableGen.py script should be run before rebuilding SciTE. Or run scite/scripts/RegenerateSource.py to regenerate all the SciTE files. The scintilla directory should be a sibling of the scite directory for Scintilla definitions to be found.

~~~lua
function ShowEOLAnnotations()
	-- On the line of the caret, show an EOL annotation and fold with some fold text
        local line = editor:LineFromPosition(editor.CurrentPos)

	editor.EOLAnnotationVisible = EOLANNOTATION_STANDARD
	editor.EOLAnnotationText[line] = " #movl   $0x37,-0x9c(%rbp) "
	editor.EOLAnnotationStyle[line] = SCE_LUA_WORD7

	-- Fold but only if line is a fold header
	if editor.FoldLevel[line] & SC_FOLDLEVELHEADERFLAG ~= 0 then
		editor.FoldDisplayTextStyle = SC_FOLDDISPLAYTEXT_STANDARD
		editor:ToggleFoldShowText(line, "/* " .. line .. " ... */")
	end
end
~~~

In user properties:
~~~properties
command.name.13.*=ShowEOLAnnotations
command.13.*=ShowEOLAnnotations
command.mode.13.*=subsystem:lua,savebefore:no,quiet:yes
~~~

Not showing the selection seems fine to me. Quite a bit of code can be removed as a consequence of not showing the selection over the EOL annotation.

**Comment by ecofriendlygeek** [comment]
@nyamatongwe  Corrected bugs in last revision. EOLAnnotation text is not shaded by the selection.

https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/6086200d0b8be607f42aa5fd1562b70e07f35b58/
scite_eola_selection

**Comment by nyamatongwe** [comment]
For performance, DrawEOLAnnotationText should check eolAnnotationVisible before calling EOLAnnotationStyledText and return early if it is EOLANNOTATION_HIDDEN. That minimizes the cost of EOL annotations unless they are turned on.

The call to GetFoldDisplayText should be moved after retrieving the EOL annotation since it won't be used unless there is an EOL annotation.

**Comment by ecofriendlygeek** [comment]
Made the suggested changes.
please review
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/7bb7cea6fa6aefea324035d29898ce5c889a6c8d/

**Comment by nyamatongwe** [comment]
The avoidance of work based on EOLANNOTATION_HIDDEN or visible should also occur in EditView::DrawEOL to avoid calling EOLAnnotationStyledText when not needed.

The changes are formatted differently from the rest of the file and should be reformatted with tabs instead of spaces.

**Comment by ecofriendlygeek** [comment]
Please review (tab instead of space and DrawEOL check)
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/cb606c86c3bed80af5b5f24821f5263aca534a3a/

**Comment by nyamatongwe** [comment]
While the SC_MOD_CHANGEEOLANNOTATION notification is sent, it isn't used to ensure the screen is updated in Editor::NotifyModified. For other annotations, there is a section here that checks for SC_MOD_CHANGEANNOTATION and calls Redraw(). To maximize the chances of seeing no update turn off caret blinking - in SciTE: caret.period=0.

**Comment by nyamatongwe** [comment]
Why try to change the contraction state height? Unlike normal annotations, EOL annotations do not take extra lines.

**Comment by ecofriendlygeek** [comment]
Removed the un-necessary code. Please reviewhttps://sourceforge.net/u/ecofriendlygeek/scintilla/ci/30217ae3fd3e49c06c28bd0dde5581271cccb76c/


    On Thursday, 11 June, 2020, 09:00:16 am IST, Neil Hodgson <notifications@github.com> wrote:  
 
 


Why try to change the contraction state height? Unlike normal annotations, EOL annotations do not take extra lines.

**Comment by nyamatongwe** [comment]
What name should appear in the credits? It can be a pseudonym like "ecofriendlygeek" if you like.

**Comment by ecofriendlygeek** [comment]
Updated the credits; please review
https://sourceforge.net/u/ecofriendlygeek/scintilla/ci/b16593058573846d7c78d3041ac79c1fa5a12447/

**Comment by nyamatongwe** [comment]
Committed with https://sourceforge.net/p/scintilla/code/ci/1b383adfdf71f97259e86316ab379bda9a5cb0f4/

Changed header ID in HTML documentation to not have spaces so file passes validation.

Changed alias definition so "EOL" acronym capitalized and bindings see "ChangeEOLAnnotation".
ali SC_MOD_CHANGEEOLANNOTATION=CHANGE_E_O_L_ANNOTATION

Reformatted to match indentation of existing code.

Switched styleMain argument of TextBackground back to int to match other code and used cast when called for EOL Annotation.

**Comment by ecofriendlygeek** [comment]
@nyamatongwe appreciate your code reviews and testing.

**Pull request closed without merging**
