### PR TITLE
For review, draw margin annotation at end of line of text

### PR DESCRIPTION
**Pull request by ecofriendlygeek**
Issue #1 - For review Drawing of EOL Annotation

### CODE REVIEW

**Comment by ecofriendlygeek** [comment]
To review Drawing of EOL Annotation

**Comment by nyamatongwe** [comment]
That draws the text OK. There are two main issues: position and drawing layers.

The position doesn't take into account other line end objects like visible line ends or fold text. Try turning visible line ends on and off. With the patch, the annotation appears on each line when wrapped. Add fold text by changing calls from ToggleFold(line) to ToggleFoldShowText(line, "folded").

The annotation appears too close to the line text for me so I expect there should be an API to set a space between the line end and annotation.

Scintilla can show background colours and markers, text, indicators and other elements in various ways to allow multiple pieces of information to be visible in one area. Drawing may be performed in 1, 2, or multiple phases based on SetPhasesDraw. Drawing phases may occlude background pixels or may be drawn with translucency, merging with the background pixels. Single phase drawing is archaic so new features do not have to support it but both 2 phase and multiple phase drawing should be supported. You should examine DrawFoldDisplayText for an example that tries to draw items in each phase to ensure that features like caret line are visible (set up with SetCaretLineVisible/SetCaretLineBack/SetCaretLineBackAlpha). Fold text is also a good example of behaviour that can be copied although there could also be differences between the features.

**Comment by ecofriendlygeek** [comment]
Need to decide whether we want to model 
1. Text and EditView::DrawLine (multi-phase)
2. Annotations and EditView::DrawAnnotation (2 phase)
3. Margins and MarginView::PaintMargin (single phase)

I think (2) above represents a reasonable amount of functionality, like boxed, indented.
We could reuse the LineAnnotation class, with a different API.
We can take care of drawing at the correct position after visible Line End and after last folded line.

I think if we want to go for (1); multi-phase/caret/folding : it would be better to consider the annotation as part of the text itself.

**Comment by nyamatongwe** [comment]
Line annotations have their own lines that are not shared with most other elements so have a simpler drawing model. Margins have limited sharing as its easy to add another margin when one margin gets too messy.

The most similar feature to this is fold text and during development that became more complex until it was implementing 4 phases.

A problem with adding the end-of-line annotation to the line text is that it would then have to be in the same encoding as the line text which has proved a limitation for fold text. This will be addressed in a future version with a way to specify that the fold text is UTF-8 even when the document is Windows-1252 or similar. Another issue is that the annotation would have to use the same styles as the line text - when line and margin annotations were added, extended styles were added so that annotations didn't have to share the 248 styles available to lexers. Right-justified end-of-line annotations would be a reasonable addition and a unified text buffer would be an obstacle to that. When a line has fold text, the most likely ordering is [line text, fold text, annotation] and this would require either spacing over the fold text or redoing its implementation to add that onto the line text.

**Comment by ecofriendlygeek** [comment]
Hi Neil,
1. Can you give me some of  your testcases (prakashsahni@yahoo.com) ?
2. We want that the solution has to consider text, fold text. annotation. 
Thanks.

**Comment by ecofriendlygeek** [comment]
Neil, Can you give me the user level code for the most difficult case, which if handled correctly, would meet the design requirements  ? This would give me a jump start.

**Comment by nyamatongwe** [comment]
You will need to look at the code to identify all the different paths and modes that are possible. Enumerating all the cases and making decisions about how to handle clashes is probably the major part of implementing this feature, not the coding. There won't be a single difficult case that covers everything but multiple pairings of features to consider.

**Comment by nyamatongwe** [comment]
Horizontal clashes between elements sharing one line are most significant. It may be worthwhile performing some more position determination in LayoutLine with results recorded in LineLayout so that can just be used when drawing. DrawFoldDisplayText decides itself where to put the fold text which makes it more difficult to share now that line end annotations may be drawn after fold text.

Vertical sharing is less of a problem but can be checked by using emoji and text that draw accents and similar above and below (Ŵༀཀུ) that may draw outside the line depending on font and platform. macOS is more likely to draw outside the line than Win32. See the original multi-phase issue at https://groups.google.com/d/topic/scintilla-interest/oXPYPFl9W7g/discussion

**Pull request merged**
